### ISSUE TITLE
XLSX.read support

### ISSUE THREAD

**Issue by hkstsony** [netanelgilad/meteor-excel#1]
Please add XLSX.read function support

Excel.prototype.read = function (file, read_opts) {
  if (this.fileType === 'xlsx') {
    return XLSX.read(file, read_opts);
  }
  else if (this.fileType == 'xls') {
    return XLS.read(file, read_opts);
  }
};

**Comment by netanelgilad** [comment]
@hkstsony Thanks!
Added.
