### ISSUE TITLE
Wrong encoding for non English characters

### ISSUE THREAD

**Issue by SarahTan** [netanelgilad/meteor-excel#10]
The product I'm working on is supposed to parse data from uploaded XLS files which have been exported from [CamCard](https://store.intsig.net/product/detail?ppid=CamCard_PC_License). However, the encoding of Chinese, Russian, Greek and Japanese characters are all wrong. i.e. `字集碼 Набор символов Κωδικοποίηση χαρακτήρων について` gives me `šÉ´¹º¿À¿¯·Ã· Ç±Á±ºÄ®ÁÉ½ kdDf WÆ¼ 01>@ A8<2>;>2`.

When I convert the file to XLSX the characters appear properly, and when I convert the XLSX file back to XLS is works as well. Unfortunately, making the user convert their file before uploading it is not a possible solution due the the product constraints.

I'm using an online file converter as I don't have Excel on my computer. Here's the [language test file](https://docs.google.com/spreadsheets/d/1x9NXmwiy8yMjjd7yOdKM5B7PuyptxEcSHrgxJ3rpZ1s/edit?usp=sharing) I'm using, which is exported from CamCard.

**Comment by SarahTan** [comment]
After looking through SheetJS/js-xls and the issues there, I suspect CamCard might be using an older version of XLS (based on [this thread](https://github.com/SheetJS/js-xls/issues/64)). It seems like the latest version of js-xls (0.7.5) is able to parse older XLS formats, but meteor-excel is using version 0.7.1 of js-xls.

**Comment by netanelgilad** [comment]
Great.  So if you would like to PR the version of the dependencies I can
merge it. I can do it later today and publish a new version.

**Comment by netanelgilad** [comment]
I released a new version with the updated deps. 0.2.4. Have fun!
