### ISSUE TITLE
Functionality question 

### ISSUE THREAD

**Issue by jsonify** [netanelgilad/meteor-excel#11]
New to Meteor here. When I place "var excel = new Excel('xlsx'); " into a excel.js file in either a client or server folder, when I run the code, I get: 

Uncaught TypeError: undefined is not a function 

So where should I be putting that file for it to work?

**Comment by netanelgilad** [comment]
You should use `new Excel(..)` only on the server since that it exists only there. Have you added the meteor excel package with `meteor add netanelgilad:excel`? if you did, then maybe you can share your code, and i'll see where the problem is.

**Comment by jsonify** [comment]
That was added as the first step. I have since placed the `excel.js` file into the server folder. To test the functionality, once a file has been uploaded, I have an `Info` button that should console log out the contents of cell `A1` and pop up an alert that states the file name and size. But alas, I get the following:

`Uncaught ReferenceError: excel is not defined`

Here is my repo: https://github.com/jsonify/meteor-upload

**Comment by netanelgilad** [comment]
I could not find exactly the part in your package where you are using the `excel` object, but any way, in your excel.js file you are doing `var excel = new Excel(...)` and that means that the excel variable will not be exposed to any other file. Try doing `excel = new Excel(...)`.

**Comment by jsonify** [comment]
My apologies for not giving a better description as to where I have my code. Here is how I'm using it:

/client/templates/home.js

```
...

Template.uploadedInfo.events({
  'click .deleteUpload':function() {
    if (confirm('Are you sure you want to delete ' + this.name)) {
      Meteor.call('deleteFile', this._id);
    }
  },
  'click .getInfo': function () {
    var workbook = excel.readFile( this.url + this.path);
    var yourSheetsName = workbook.SheetNames;
    console.log("Get Some Cell from it: " + workbook.Sheets[yourSheetsName[0]]['A1'].v );
    alert('File: '+ this.name + " is " + (this.size)/1000000 + 'MB and is located: ' + this.url+this.path);
  }
})
```

I have also removed the `var` from the declaration, and still no luck.

**Comment by netanelgilad** [comment]
OK I got it now.
You are trying to use the excel object in the client when the `excel,js` file is in the server, and objects declared on server files are not defined for files on the client.
But before you tried to put the `excel.js` file in the client. That didn't work because the Excel object (notice the Uppercase E) is only available on the server.
So what you need to do is handle your excel files only on the server side and expose that using a `Meteor.Method` so the client can call it.
Hope that helps...

**Comment by jsonify** [comment]
So, you're saying I should have the .xlsx files be stored in the `/server` rather than the `/client` and that will give me access to it via a Meteor.Method from the client? I think that makes sense.

**Comment by jsonify** [comment]
Well, after some changes I think I'm getting closer, but still not there. Probably due to my lack of knowing what I'm doing completely. Now the `Info` button calls the correct Method, but it says the file doesn't exist:

`Exception while invoking method 'getFileInfo' Error: ENOENT, no such file or directory '/server/uploads/test-schedule.xlsx'`

Is it that I'm just not calling it correctly?

**Comment by netanelgilad** [comment]
Hey @jsonify,
you should put your files in the /private folder and then used the assets api. Have a look here: http://docs.meteor.com/#/full/assets
