### ISSUE TITLE
"Failed - Server problem" when trying to download

### ISSUE THREAD

**Issue by rafaelquintanilha** [netanelgilad/meteor-excel#13]
Hello,

I'm following [this meteorpad](http://meteorpad.com/pad/2hjNqmwHjDvkxvLC5/Leaderboard), which has been very helpful. My application has a pretty similar logic, an export button that must be downloaded performing some operations when building the sheet.

Although it works flawlessly in your example (it does download), when I port to my app I'm gettin "Failed - Server Problem" during the download. I do get the local path, for instance: /gridfs/temporaryFiles/164f1128a50093f5f43ada8f

I'm kinda lost if I'm missing some package or initial configuration. I don't have GridFS, for example, only those required in the pad.

What could I be missing here?

PS: I'm using Google Chrome (download doesn't work even in your example when running on Firefox. But this isn't a concern right now).

**Comment by netanelgilad** [comment]
Can you share your code in any way and i'll have a look?

I know about the issue with Firefox, it has to do with the way I initiate the download which is not really cross-browser, but i never actually got to finding the best way to do it.

**Comment by rafaelquintanilha** [comment]
This is my method (server.js):

```
Meteor.methods({
    downloadExcelFile: function() {
        var Future = Npm.require('fibers/future');
        var futureResponse = new Future();

        var excel = new Excel('xlsx'); // Create an excel object  for the file you want (xlsx or xls)
        var workbook = excel.createWorkbook(); // Create a workbook (equivalent of an excel file)
        var worksheet = excel.createWorksheet(); // Create a worksheet to be added to the workbook

        worksheet.writeToCell(0,0, 'Apontamentos');
        worksheet.mergeCells(0,0,0,1); // Example : merging files
        worksheet.writeToCell(1,0, 'Nome');
        worksheet.writeToCell(1,1, 'Produção');

        var row = 2;
        Apontamentos.find().forEach(function(a) {
            console.log(a);
            worksheet.writeToCell(row, 0, a.safrista_id);
            worksheet.writeToCell(row, 1, a.production);
            row++;
        });     

        workbook.addSheet("Apontamentos", worksheet);

        mkdirp('tmp', Meteor.bindEnvironment(function (err) {
            if (err) {
                console.log('Error creating tmp dir', err);
                futureResponse.throw(err);
            }
            else {
                var uuid = UUID.v4();
                var filePath = './tmp/' + uuid;
                workbook.writeToFile(filePath);

                temporaryFiles.importFile(filePath, {
                    filename : uuid,
                    contentType: 'application/octet-stream'
                }, function(err, file) {
                    if (err) {
                        futureResponse.throw(err);
                    }
                    else {
                        futureResponse.return('/gridfs/temporaryFiles/' + file._id);
                    }
                });
            }
        }));

        return futureResponse.wait();
    }
});
```

This is my both.js:

```
temporaryFiles = new FileCollection('temporaryFiles',
  { resumable: false,   // Enable built-in resumable.js upload support
    http: [
      { method: 'get',
        path: '/:_id',  // this will be at route "/gridfs/temporaryFiles/:_id"
        lookup: function (params) {  // uses express style url params
          return { _id: params._id};       // a query mapping url to myFiles
        }
      },
      { method: 'post',
        path: '/:_id',
        lookup: function (params) {
          return {
            _id: params._id
          }
        }}
    ]
  }
);
```

And in my template:

```
Template.safristaPopover.events({
    "click #export": function() {
        Meteor.call('downloadExcelFile', function(err, fileUrl) {
            console.log(fileUrl);           
            var link = document.createElement("a");
            link.download = 'Apontamentos.xlsx';
            link.href = fileUrl;
            link.click();           
        });
    }
});
```

**Comment by skastr0** [comment]
I had the same error and fixed it by adding the temporaryFiles.allow part from the same meteorpad.

```
temporaryFiles.allow({
    insert: function( userId, file ) {
      return true;
    },
    remove: function( userId, file ) {
      return true;
    },
    read: function( userId, file ) {
      return true;
    },
    write: function( userId, file, fields ) {
      return true;
    }
  });
```

**Comment by netanelgilad** [comment]
@rafaelquintanilha Did @skastr0 answer help you?

**Comment by adrianbj** [comment]
Hi everyone,

I am having the same problem here. I am seeing the excel file here:

```
/path/to/.meteor/local/build/programs/server/tmp/c05db38b-52ed-49fa-b5dd-0f0cac2e8ea2
```

but nothing is being downloaded. There is no /gridfs/temporaryFiles anywhere though - is that possibly part of my problem? I assumed that isn't a real filesystem path, but rather a database reference to the file in the tmp path shown above.

I have the temporaryFiles.allow all set up. I even tried adding back in insecure and autopublish, but it made no difference.

Thanks for any suggestions on how to fix.

**Comment by skastr0** [comment]
If you have the temporaryFiles.allow set up and the name of the excel file I assume opening an url
<your-website>/gridfs/temporaryFiles/c05db38b-52ed-49fa-b5dd-0f0cac2e8ea2 should work.

If not then maybe it's something with the way you create the fileCollection? Or try adding ?filename=<filename>.xls(x) to the url.

**Comment by adrianbj** [comment]
Sorry about that - as usual, you're just about to give up, you make a comment on an issue, then figure it out - it was a problem with how I was calling the download method from the client.

It case it helps someone else, it is critical to use this call the downloadExcelMethod from the client like this. I just overlooked how the server method relied on link.x items to appropriately trigger the download.

```
    Meteor.call('downloadExcelFile', function(err, fileUrl) {
      console.log(fileUrl);
      var link = document.createElement("a");
      link.download = 'Players leaderboard.xlsx';
      link.href = fileUrl;
      link.click();
    });
```

Thanks for a great tool!
