### ISSUE TITLE
Problem with binary write

### ISSUE THREAD

**Issue by cskaandorp** [netanelgilad/meteor-excel#22]
Hi, 

I have a problem with the write method on the workbook. I have this piece of very simple test-code, straight from the examples:

``` javascript
Meteor.methods

  export: (data) ->

    excel = new Excel('xlsx')
    workbook = excel.createWorkbook()
    worksheet = excel.createWorksheet()

    worksheet.writeToCell(0,0, 'Players leaderboard')
    workbook.addSheet('MySheet', worksheet)

    wopts = { bookType: 'xlsx', bookSST: false, type: 'binary' }

    # workbook.writeToFile("/Users/casperkaandorp/test.xlsx")
    wbout = workbook.write(wopts)

    return wbout
```

This doesn't work. On the console I read:

Exception while invoking method 'export' TypeError: Object [object Object] has no method 'write'

I don't get it. The writeToFile method works fine, I've seen the write-implementation but nevertheless Meteor claims not to have the write-method. Any pointers on this? Thanks and thanks for your great work!

**Comment by mandreko** [comment]
I'm running into this same issue. I can't write my Excel file :(

**Comment by mandreko** [comment]
I'm still running into this issue, and am not experienced enough with meteor or node yet to figure out what's causing it. I agree with @cskaandorp that I see the function for 'write' declared in the package, but it sure doesn't work.

**Comment by cskaandorp** [comment]
I finally got it 'working'. So far none of the maintainers responded on this and the issue above still does not work.

This is what I did: I have downloaded this package and added it as a **local package**. Don't ask me why, but that got rid of the Type-error. 
I verified that I did not had some older version of this package going which caused the error. 

Anyway, this is not the end of it. The write function should deliver a string that needs to be converted to an ArrayBuffer so you can put it in a blob. I have seen several example functions which are supposed to do it. None of them actually worked. On closer inspection there was something strange, it seemed that instead of the important bit, some other array was returned. When I changed this, I got it to work. Here's my code (again, it runs this package locally, and in coffeescript):

Server:

``` javascript
  download: ->    
    excel = new Excel('xlsx')
    # create a workbook
    workbook = excel.createWorkbook()
    # create a sheet on this motherfucker
    worksheet = excel.createWorksheet()
    worksheet.writeToCell(0,0, 'Some value')
    worksheet.writeToCell(0,1, 'Another Value')

    # add sheet to workbook
    workbook.addSheet('Some Sheet', worksheet)

    wopts = { bookType: 'xlsx', bookSST: false, type: 'binary' }
    wbout = workbook.write(wopts)

    s2ab = (s) ->
      buf = new ArrayBuffer(s.length)
      view = new Uint8Array(buf)
      for i in [0..s.length]
        view[i] = s.charCodeAt(i) & 0xFF
      return view # NOT RETURN buf

    return s2ab(wbout)
```

Client:

``` javascript
      Meteor.call 'download', (error, result) ->
        unless error
          console.log result
          saveAs(new Blob([result], { type: '' }), 'test.xlsx')
        else
          console.log error
```

Apart from the s2ab thing, I am still puzzled why this works when I add the package from local. So if anybody has some answers on this... that'd be great. Thanks, 

Casper

**Comment by mandreko** [comment]
That's super weird. It totally worked for me too... I'd love to not have a weird workaround though.

**Comment by netanelgilad** [comment]
Hey guys,
Sorry to have been ignoring this for so long. Didn't keep up with the repo. 
I haven't released a new version that includes the write function to atmospherejs, so that is why is was working locally but not from the published version. Update to 0.2.5 and it should work.

**Comment by mandreko** [comment]
Thank you. I can confirm that this fixed it for me.

**Comment by cskaandorp** [comment]
For me as well. Thanks from me as well! And thanks for your work in general.
