### ISSUE TITLE
cant get it work

### ISSUE THREAD

**Issue by amitrahav** [netanelgilad/meteor-excel#4]
XLSX returns undefined function.
i've downloaded and install the package.
what am i doing wrong?

**Comment by netanelgilad** [comment]
The object that is exported by meteor excel is Excel. You can work with xlsx files like with: 
`var excel = new Excel('xlsx');`

**Comment by amitrahav** [comment]
Yet,  undefined is not a function. 

what could be the reason?

**Comment by netanelgilad** [comment]
can you share some code? or a reproduction if you can... I'll take a look.

**Comment by amitrahav** [comment]
i'm actually just logging the piece of code you wrote after installing the package..

**Comment by netanelgilad** [comment]
on the client or the server?

**Comment by amitrahav** [comment]
client

**Comment by amitrahav** [comment]
ok. it created an object on the server side:

```
{ fileType: 'xlsx', utils: { fileType: 'xlsx' } }
```

but i cant write worksheets into it...
`new Workbook()` return function undefined again.

**Comment by netanelgilad** [comment]
You need to use excel.createWorkbook() to create a new workbook.
Check out the new full example for exporting a file to excel and downloading.
Hope this helps..

**Comment by amitrahav** [comment]
hey, nice work on the documentation.
the excel file in your example is kind of complax.

is there a way to use the `writeFile` function from xslx.js? (https://github.com/SheetJS/js-xlsx#writing-workbooks)

here is an example for how it should work: http://meteorpad.com/pad/a5YfgAsXHiLWAkRaZ/Copy%20of%20Leaderboard

**Comment by netanelgilad** [comment]
Yep you can just do workbook.writeToFile(filePath); which internally uses writeFile.

**Comment by amitrahav** [comment]
http://meteorpad.com/pad/a5YfgAsXHiLWAkRaZ/Copy%20of%20Leaderboard

return undefined

**Comment by netanelgilad** [comment]
the workbook.writeToFile function writes the workbook to a file on the filesystem and it doesn't return anything... what do you want it to return?
