### ISSUE TITLE
upload file type

### ISSUE THREAD

**Issue by amitrahav** [netanelgilad/meteor-excel#5]
on upload file the type for .xlsx is "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" and for .xsl is "application/vnd.ms-excel".

your plugin does not allow anything but "xslx" and "slx". its relevant for writing file, but how does it relevant for reading files?

example:
http://meteorpad.com/pad/a5YfgAsXHiLWAkRaZ/Copy%20of%20Leaderboard

**Comment by cristiandley** [comment]
@amitrahav this package is just a wrap of [js-xlsx](https://github.com/SheetJS/js-xlsx), if you check their documentation. Some XLSX use jszip library to be able to read/parse them.

**Comment by netanelgilad** [comment]
@amitrahav MeteorPad seems to be offline. What you are describing seems like a MIME type which is different from the file extension itself and is more descriptive. When you create the excel object can't you just give it the matching file extension?
